import "@/styles/globals.css";
import { Poppins } from "next/font/google";

const poopins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "My pay landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-langing text-[#F7F7F7] ${poopins.className}`}>
        {children}
      </body>
    </html>
  );
}
