import DashboardLayout from "@/components/Layout/DashboardLayout";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by tarifhasan674@gmail.com",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardLayout childrens={children} />
        <Toaster />
      </body>
    </html>
  );
}
